language: node_js
sudo: false

node_js:
- "10"
- "12"
- "14"

cache: npm

git:
  depth: false

script:
  npm test

after_success:
  - if [[ "$TRAVIS_NODE_VERSION" == 14 ]]; then npm run coveralls; fi
